### ISSUE TITLE
Doesn't work with Checkstyle-IDEA plugin

### ISSUE THREAD

**Issue by vsnitko** [tfij/check-tfij-style#41]
I have an error when trying to use this extention with [Checkstyle-IDEA plugin](https://plugins.jetbrains.com/plugin/1065-checkstyle-idea)

When plugin installed, go to `IDEA Settings -> Tools -> Checkstyle -> Configuration File -> +` and select [checkstyle.xml](https://github.com/tfij/check-tfij-style/blob/main/sample/sample-maven-project/config/checkstyle/checkstyle.xml) file from this repository. I'm getting the error 
```
The Checkstyle rules file could not be parsed.
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - cannot initialize module MethodParameterAlignment - Unable to instantiate 'MethodParameterAlignment' class, it is also not possible to instantiate it as .MethodParameterAlignment, MethodParameterAlignmentCheck, .MethodParameterAlignmentCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:480)
	at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.configure(AbstractAutomaticBean.java:207)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module MethodParameterAlignment - Unable to instantiate 'MethodParameterAlignment' class, it is also not possible to instantiate it as .MethodParameterAlignment, MethodParameterAlignmentCheck, .MethodParameterAlignmentCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:128)
	at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.configure(AbstractAutomaticBean.java:207)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:475)
	... 7 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'MethodParameterAlignment' class, it is also not possible to instantiate it as .MethodParameterAlignment, MethodParameterAlignmentCheck, .MethodParameterAlignmentCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:215)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:119)
	... 9 more
```

I don't very need this extention to be supported by Checkstyle-IDEA (but it would be very nice if it is), the issue is that all other rules in checkstyle.xml are also not parsed and it doesn't work at all

**Comment by tfij** [comment]
Hi @vsnitko, 
Thanks for the message.

I've just reproduce the issue.

To make it works, go to `IDEA Settings -> Tools -> Checkstyle -> Third-Party Checks -> +` and add the `check-tfij-stile` jar.
Then [Checkstyle-IDEA plugin](https://plugins.jetbrains.com/plugin/1065-checkstyle-idea) should successfully pars xml with additional checks from the lib.

**Comment by vsnitko** [comment]
It works. Thank you!
